// Ordered from closest (<1km) to farthest (~10km) from your home
export const NEARBY_LIBRARIES_ORDER = [
  "Fahrbibliothek Mitte 5",
  "Bruno-Loesche-Bibliothek",
  "Hansabibliothek",
  "Kurt-Tucholsky-Bibliothek (Mitte)",
  "Bibliothek Tiergarten Süd",
  "Bezirkszentralbibliothek Philipp Schaeffer",
  "Schiller-Bibliothek", // e.g., "Mitte: Schiller-Bibliothek"
  "Stadtteilbibliothek Schöneberg-Nord",
  "Berliner Stadtbibliothek (BStB)",
  "Berlin-Sammlungen",
  "Amerika-Gedenkbibliothek (AGB)",
  "Außenmagazin",
  "Kinder- und Jugendbibliothek mit Lernzentrum",
  "Thomas-Dehler-Bibliothek",
  "Heinrich-Schulz-Bibliothek mit Musikabteilung",
  "Mittelpunktbibliothek Schöneberg",
  "Bibliothek am Luisenbad",
  "Fahrbibliothek Mitte Bus 1",
  "Fahrbibliothek Mitte Bus 2",
  "Fahrbibliothek Mitte Bus 3",
  "Dietrich-Bonhoeffer-Bibliothek",
  "Stadtteilbibliothek Friedrich von Raumer",
  "Bibliothek am Schäfersee Stadtteilbibliothek Reinickendorf-Ost",
  "Mittelpunktbibliothek Wilhelm Liebknecht / Namik Kemal",
  "Bettina-von-Arnim-Bibliothek",
  "Stadtteilbibliothek Halemweg",
  "Ingeborg-Bachmann-Bibliothek",
  "Bibliothek am Wasserturm",
  "Museum Pankow - Termin nach Absprache",
  "Familienbibliothek Else Ury",
  "Kleiner Bücherbus Reinickendorf",
  "Kurt-Tucholsky-Bibliothek (Pankow)",
  "Heinrich-Böll-Bibliothek",
  "Bibl. Reinickendorf - West",
  "Johanna-Moosdorf-Bibliothek",
  "Adolf-Reichwein-Bibliothek",
  "Bezirkszentralbibliothek Tempelhof-Schöneberg",
  "Helene-Nathan-Bibliothek",
  "Eberhard-Alexander-Burgh-Bibliothek",
  "Janusz-Korczak-Bibliothek",
  "Bezirkszentralbibliothek Pablo Neruda",
  "BiboBike (mobile Bibliotheksstation)",
  "Wolfdietrich-Schnurre-Bibliothek",
  "Stadtteilbibliothek Alt-Treptow Manfred Bofinger",
  "Ingeborg-Drewitz-Bibliothek",
  "Fahrbibliothek Tempelhof-Schöneberg",
  "Blindenbibliothek Betty Hirsch",
  "Egon-Erwin-Kisch-Bibliothek",
  "Stadtteilbibliothek Haselhorst"
];
